#!/usr/bin/env bash
# Plan 00102 — triage.bash
#
# PURPOSE: gather grounded FACTS about why Dash to Dock does not hide behind an
# un-maximised Ptyxis window. Fact-finding only — it renders no verdict and changes
# nothing (CLAUDE/PlanScriptStandards.md R9).
#
# RUN ON THE HOST, FROM THE TERMINAL THAT HAS THE PROBLEM (Ptyxis), un-maximised:
#   ./CLAUDE/Plan/00102-dash-to-dock-does-not-dodge-ptyxis-terminal/triage.bash
#
# Running it from Ptyxis matters: the window-tracker probe reports the FOCUSED window,
# and the whole question is how GNOME Shell classifies that window.
#
# EFFECT ON THE HOST: every leg is READ-ONLY. It reads dconf, package metadata, desktop
# files and the Shell's window list over D-Bus. Nothing is written or toggled.
#
# Usage: ./triage.bash [-h|--help]
#
# EXIT CODES:
#   0  every probe reached a definite answer
#   1  at least one probe could not be answered; the failing leg names itself. This means
#      the FACT-FINDING is incomplete, not that the desktop is broken.
#  64  usage error
set -euo pipefail

# ── R1 bootstrap: script-relative, filesystem-only, bounded at the repo boundary ──────────
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage.bash [-h|--help]

Gathers facts about the terminal in use, the Dash to Dock package and its
intellihide settings, and how GNOME Shell classifies the focused window.

Host-only, read-only, safe to re-run. Run it FROM the Ptyxis window that
fails to hide the dock. Writes a report into
<this plan folder>/triage-runs/<timestamp>/ and names it on completion."

plan_mode gather
plan_parse_common_flags "$@"

if [[ "${#PLAN_REMAINING_ARGS[@]}" -gt 0 ]]; then
    printf '[FATAL] unknown argument(s): %s\n' "${PLAN_REMAINING_ARGS[*]}" >&2
    printf '%s\n' "${PLAN_USAGE}" >&2
    exit 64
fi

plan_require_host "it reads the host's dconf, installed packages and the GNOME Shell session bus"

plan_start_log auto

REPORT="${PLAN_RUN_DIR}/plan-00102-triage-report.md"
readonly REPORT

{
    printf '# Plan 00102 — triage report\n\n'
    printf 'Generated by CLAUDE/Plan/00102-dash-to-dock-does-not-dodge-ptyxis-terminal/triage.bash on the HOST.\n\n'
    printf -- '- repo root (resolved from the script, not the cwd): %s\n' "${PLAN_REPO_ROOT}"
    printf -- '- run directory: %s\n' "${PLAN_RUN_DIR}"
} >"${REPORT}"

# Legs are commands, not local functions (PlanScriptStandards, reference skeleton).
plan_gather_leg "terminal, dock package, intellihide settings, focused-window classification" \
    bash "${PLAN_SCRIPT_DIR}/probe-dock.bash" "${REPORT}"

plan_finish
