#!/usr/bin/env bash
# triage-buckets.bash — does the API report a Fable bucket, and on which probe model?
#
# Fact-finding only: renders no verdict (R9), changes nothing on the host.
#
# Separate from this plan's triage.bash, which answers a different question (the utilisation
# SCALE, from the cache, spending nothing).
#
# RUN ON THE HOST:
#   ./CLAUDE/Plan/00101-ccy-token-usage-via-ratelimit-headers/triage-buckets.bash
#
# COST: this one SPENDS. Two billed requests by default, one per probe model, max_tokens=1
# and a single character of input. The Fable probe draws on the Fable allowance it reports.
#
# Usage: ./triage-buckets.bash [-h|--help]
#
# EXIT CODES:
#   0  the probe reached a definite answer
#   1  the fact-finding is incomplete; the failing leg names itself
#  64  usage error
set -euo pipefail

# ── R1 bootstrap: script-relative, filesystem-only, bounded at the repo boundary ──────────
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage-buckets.bash [-h|--help]

Asks which rate-limit buckets the API reports, and whether the answer depends on
the model the probe is sent with. Written because ccy shows a 5-hour bar and a
weekly bar and nothing for the Fable allowance.

HOST-ONLY. Changes nothing, but it is NOT free: one billed POST /v1/messages per
probe model (max_tokens=1, one character in), against the allowance it reports.
Default list is Haiku then Fable, so two requests.

  PROBE_MODELS   space-separated model ids to probe instead of the default
  PROBE_ACCOUNT  1-based index into the sorted token pool, or 'all' (default: 1)

One request is made per account-and-model pair, so 'all' multiplies the cost by
the size of the pool. To find which account can reach Fable without re-probing
Haiku on every one of them:

  PROBE_ACCOUNT=all PROBE_MODELS=claude-fable-5-1 ./triage-buckets.bash

Writes a report into <this plan folder>/triage-buckets-runs/<timestamp>/ and
names it on completion."

plan_mode gather
plan_parse_common_flags "$@"

# Reject unknown arguments rather than ignoring them.
if [[ "${#PLAN_REMAINING_ARGS[@]}" -gt 0 ]]; then
    printf '[FATAL] unknown argument(s): %s\n' "${PLAN_REMAINING_ARGS[*]}" >&2
    printf '%s\n' "${PLAN_USAGE}" >&2
    exit 64 # EX_USAGE — never confusable with a real probe result
fi

# Refuse the container BEFORE opening a log: there is no token mounted there, so the run
# would report "no tokens" and that reads as a fact about the pool (R2).
plan_require_host "the ccy token pool lives on the host; a CCY container has no token mounted"

plan_start_log auto

REPORT="${PLAN_RUN_DIR}/plan-00101-bucket-report.md"
readonly REPORT

{
    printf '# Plan 00101 — which rate-limit buckets does the API report?\n\n'
    printf 'Generated by triage-buckets.bash on the HOST.\n\n'
    printf -- '- run directory: %s\n' "${PLAN_RUN_DIR}"
    printf -- '- probe models: %s\n' "${PROBE_MODELS:-claude-haiku-4-5-20251001 claude-fable-5-1 (default)}"
} >"${REPORT}"

# Legs are COMMANDS, not local functions: a function passed by name is invoked indirectly, so
# the linter reports its whole body as unreachable (SC2317) — and suppressing that is banned
# here (R11).
plan_gather_leg "rate-limit bucket headers, per probe model" \
    bash "${PLAN_SCRIPT_DIR}/probe-bucket-headers.bash" "${REPORT}"

plan_finish
