#!/usr/bin/env bash
# Plan 00111 — triage.bash
#
# PURPOSE: for an incident where many terminals died at once, gather the facts that separate a
# memory kill from a terminal-emulator death, and record whether any CCY session is currently
# insulated from its terminal. Fact-finding only — it renders no verdict and changes nothing
# (CLAUDE/PlanScriptStandards.md R9).
#
# RUN ON THE HOST:
#   ./CLAUDE/Plan/00111-terminal-death-takes-all-ccy-sessions/triage.bash
#
# Runnable from any directory: the repo root comes from the boundary-bounded marker walk (R1),
# not from the cwd.
#
# WHY IT EXISTS: the 2026-09-13 incident presented as an OOM kill and was not one. Establishing
# that took a long manual journal dig across four separate negatives (kernel ring, systemd-oomd,
# coredumps, memory headroom) before the actual cause — a Wayland client error severing Ptyxis,
# which owns every window and tab in one process — became visible. Next time that should be one
# command. The four OOM negatives matter as much as the positive finding: a wrong OOM diagnosis
# leads to memory limits and reduced concurrency, which would degrade the workstation while
# leaving the real fault in place.
#
# WHY THE HOST AND NOT THE CONTAINER: a container sees neither the host kernel ring, nor
# systemd-oomd, nor coredumps, nor the compositor's log. Every question here would come back
# confidently wrong. plan_require_host enforces that rather than asking politely (R2).
#
# EFFECT ON THE HOST: read-only throughout. It reads the journal, /proc and process state.
# Nothing is installed, started, stopped or killed — in particular it does NOT reap the
# orphaned pty-less claude processes it reports, because destroying evidence is not triage.
#
# Idempotent — re-run freely; each run gets its own timestamped directory, so no run clobbers a
# previous run's evidence.
#
# Usage: ./triage.bash [-h|--help]
#
# EXIT CODES (they agree with the text — no "reported a problem but exited 0"):
#   0  every question reached a definite answer, including a definite "absent"
#   1  at least one question could not be answered; the failing leg names itself. This means
#      the FACT-FINDING is incomplete, not that the host is broken.
#  64  usage error
set -euo pipefail

# ── R1 bootstrap: script-relative, filesystem-only, bounded at the repo boundary ──────────
# Copy this block verbatim into every plan script. See CLAUDE/PlanScriptStandards.md R1.
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage.bash [-h|--help]

Gathers the facts that distinguish a memory kill from a terminal-emulator death
after an incident where many terminals died at once, and records whether any CCY
session is presently insulated from its terminal.

Host-only, read-only, safe to re-run. Writes a report into
<this plan folder>/triage-runs/<timestamp>/ and names it on completion."

plan_mode gather
plan_parse_common_flags "$@"

# Reject unknown arguments rather than ignoring them.
if [[ "${#PLAN_REMAINING_ARGS[@]}" -gt 0 ]]; then
    printf '[FATAL] unknown argument(s): %s\n' "${PLAN_REMAINING_ARGS[*]}" >&2
    printf '%s\n' "${PLAN_USAGE}" >&2
    exit 64 # EX_USAGE — never confusable with a real probe result
fi

# Refuse the container BEFORE opening a log, so a wrong-environment run fails immediately and
# leaves no half-written report to be mistaken for evidence.
plan_require_host "it reads the host kernel ring, systemd-oomd, coredumps, the compositor's log and host process state"

plan_start_log auto

# The report lands in the per-run directory, which plan_finish names on the way out (R10). It
# is inside the repo so the agent reads it at the same path the operator sees; it is gitignored
# by the "*-runs/" rule in CLAUDE/Plan/.gitignore so an unscrubbed dump of host state is never
# committed; and it is per-run so re-running never overwrites earlier evidence.
REPORT="${PLAN_RUN_DIR}/plan-00111-triage-report.md"
readonly REPORT

# The header avoids markdown backticks deliberately: inside a single-quoted printf format a
# backtick reads as command substitution to shellcheck (SC2016), and a suppression is not an
# option (R11).
{
    printf '# Plan 00111 — triage report\n\n'
    printf 'Generated by CLAUDE/Plan/00111-terminal-death-takes-all-ccy-sessions/triage.bash on the HOST.\n\n'
    printf 'Reads as a set of independent questions. The four OOM negatives (sections 1-4) are\n'
    printf 'each sufficient alone to rule out a memory kill; section 5 is what found the real\n'
    printf 'cause on 2026-09-13; section 7 states whether the defence is in place yet.\n\n'
    printf -- '- repo root (resolved from the script, not the cwd): %s\n' "${PLAN_REPO_ROOT}"
    printf -- '- run directory: %s\n' "${PLAN_RUN_DIR}"
} >"${REPORT}"

# The leg is a COMMAND, not a local function: a function passed to plan_gather_leg by name is
# invoked indirectly, and `shellcheck -x` would report its whole body as unreachable (SC2317),
# which cannot be suppressed here (R11).
plan_gather_leg "memory kill vs terminal death, and CCY session insulation" \
    bash "${PLAN_SCRIPT_DIR}/probe-mass-terminal-death.bash" "${REPORT}"

plan_finish
