#!/usr/bin/env bash
# Plan 00103 — triage.bash
#
# PURPOSE: gather grounded FACTS about why the Slack Flatpak rejects a .md file dropped
# from Nautilus ("a type of file not supported by Slack"). Fact-finding only — it renders
# no verdict and changes nothing (CLAUDE/PlanScriptStandards.md R9).
#
# RUN ON THE HOST, in the graphical session that has the problem:
#   ./CLAUDE/Plan/00103-slack-flatpak-rejects-md-dropped-from-nautilus/triage.bash \
#       --file ~/path/to/mapping-clarifications-business-questions.md
#
# --file is the exact file that fails to drop. Without it the sandbox-visibility and
# MIME-typing probes have nothing to test and the run FAILS rather than emit an empty
# section that reads as "nothing wrong".
#
# EFFECT ON THE HOST: every leg is READ-ONLY. It reads flatpak metadata and overrides,
# runs harmless read-only commands (stat, cat of the mime globs) INSIDE the Slack sandbox,
# lists processes and reads Slack's local log directory. Nothing is written or toggled.
#
# Usage: ./triage.bash --file <path> [-h|--help]
#
# EXIT CODES:
#   0  every probe reached a definite answer
#   1  at least one probe could not be answered; the failing leg names itself. This means
#      the FACT-FINDING is incomplete, not that Slack is broken.
#  64  usage error
set -euo pipefail

# ── R1 bootstrap: script-relative, filesystem-only, bounded at the repo boundary ──────────
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage.bash --file <path-to-the-md-that-fails> [-h|--help]

Gathers facts about the Slack Flatpak (version, sandbox permissions, overrides),
whether the given file is readable INSIDE the sandbox, how the sandbox and the
host each MIME-type it, how Slack is running (Wayland or X11), the portal
services, and any recent upload-related lines in Slack's own log.

Host-only, read-only, safe to re-run. Writes a report into
<this plan folder>/triage-runs/<timestamp>/ and names it on completion."

plan_mode gather
plan_parse_common_flags "$@"

DROP_FILE=""
i=0
while [[ "${i}" -lt "${#PLAN_REMAINING_ARGS[@]}" ]]; do
    arg="${PLAN_REMAINING_ARGS[${i}]}"
    case "${arg}" in
        --file)
            i=$((i + 1))
            if [[ "${i}" -ge "${#PLAN_REMAINING_ARGS[@]}" ]]; then
                printf '[FATAL] --file needs a path\n' >&2
                printf '%s\n' "${PLAN_USAGE}" >&2
                exit 64
            fi
            DROP_FILE="${PLAN_REMAINING_ARGS[${i}]}"
            ;;
        --file=*)
            DROP_FILE="${arg#--file=}"
            ;;
        *)
            printf '[FATAL] unknown argument: %s\n' "${arg}" >&2
            printf '%s\n' "${PLAN_USAGE}" >&2
            exit 64
            ;;
    esac
    i=$((i + 1))
done

if [[ -z "${DROP_FILE}" ]]; then
    printf '[FATAL] --file is required: the probes test the exact file that fails to drop.\n' >&2
    printf '%s\n' "${PLAN_USAGE}" >&2
    exit 64
fi
if [[ ! -f "${DROP_FILE}" ]]; then
    printf '[FATAL] --file %s is not a regular file on the host, so nothing can be learnt about it.\n' "${DROP_FILE}" >&2
    exit 64
fi
DROP_FILE="$(cd "$(dirname "${DROP_FILE}")" && pwd -P)/$(basename "${DROP_FILE}")"

plan_require_host "it inspects the host's flatpak installation, runs commands inside the Slack sandbox and lists host processes"

plan_start_log auto

REPORT="${PLAN_RUN_DIR}/plan-00103-triage-report.md"
readonly REPORT

{
    printf '# Plan 00103 — triage report\n\n'
    printf 'Generated by CLAUDE/Plan/00103-slack-flatpak-rejects-md-dropped-from-nautilus/triage.bash on the HOST.\n\n'
    printf -- '- repo root (resolved from the script, not the cwd): %s\n' "${PLAN_REPO_ROOT}"
    printf -- '- run directory: %s\n' "${PLAN_RUN_DIR}"
    printf -- '- file under test: %s\n' "${DROP_FILE}"
} >"${REPORT}"

# Legs are commands, not local functions (PlanScriptStandards, reference skeleton).
plan_gather_leg "slack flatpak, sandbox visibility of the file, MIME typing, session, portals, slack log" \
    bash "${PLAN_SCRIPT_DIR}/probe-slack.bash" "${REPORT}" "${DROP_FILE}"

plan_finish
