#!/usr/bin/env bash
# Plan 00110 — triage.bash
#
# PURPOSE: answer the Phase-0 host questions of DESIGN.md §0 (U1, U2, U4, U5, U7, U8) plus the
# lab prerequisites (KVM, reflink, space, virtiofsd) with facts read from the HOST, so the
# decision gate of §9 T0.2 is made on a report rather than an assumption. Fact-finding only —
# it renders no verdict and changes nothing (CLAUDE/PlanScriptStandards.md R9).
#
# RUN ON THE HOST:
#   ./CLAUDE/Plan/00110-vm-lifecycle-acceptance-testing/triage.bash
#
# Runnable from any directory: the repo root comes from the boundary-bounded marker walk (R1),
# not from the cwd.
#
# WHY THE HOST AND NOT THE CONTAINER: KVM, the lab filesystem, libvirt, the user's group
# membership and linger state are all properties of the host. A container answers every one of
# them about itself, confidently and wrongly. plan_require_host enforces that (R2).
#
# EFFECT ON THE HOST: read-only, with one stated exception — the reflink probe creates two
# small files under the lab directory's nearest existing ancestor and removes them again,
# because whether `cp --reflink=always` succeeds THERE is the fact being established and it
# cannot be read without trying. Nothing is installed, started, stopped or rebuilt. In
# particular the U7 probes that would start ccy without a credential or run `ccy --rebuild`
# are NOT run here: both are state changes on a workstation with live sessions, and they are
# recorded as deferred to the guest rather than silently skipped.
#
# SUDO: the U5 group listing runs `sudo -n dnf group list`, because dnf5 keeps its system
# state root-only. That is the only privileged command, and it is read-only.
#
# Idempotent — re-run freely; each run gets its own timestamped directory.
#
# Usage: ./triage.bash [-h|--help]
#
# EXIT CODES (they agree with the text — no "reported a problem but exited 0"):
#   0  every question reached a definite answer, including a definite "absent" or "deferred"
#   1  at least one question could not be answered; the failing leg names itself. This means
#      the FACT-FINDING is incomplete, not that the host is unfit for the lab.
#  64  usage error
set -euo pipefail

# ── R1 bootstrap: script-relative, filesystem-only, bounded at the repo boundary ──────────
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage.bash [-h|--help]

Answers the Phase-0 host questions for the VM acceptance lab (DESIGN.md §0:
U1, U2, U4, U5, U7, U8) plus KVM, reflink, disk headroom and virtiofsd.

Host-only. Read-only apart from a create-and-remove reflink probe under the
lab directory. Safe to re-run. Writes a report into
<this plan folder>/triage-runs/<timestamp>/ and names it on completion."

plan_mode gather
plan_parse_common_flags "$@"

if [[ "${#PLAN_REMAINING_ARGS[@]}" -gt 0 ]]; then
    printf '[FATAL] unknown argument(s): %s\n' "${PLAN_REMAINING_ARGS[*]}" >&2
    printf '%s\n' "${PLAN_USAGE}" >&2
    exit 64
fi

plan_require_host "it reads KVM, the lab filesystem, libvirt, group membership and linger state of the host"

# dnf5's system state is root-only, so the U5 group listing needs sudo even though it is
# read-only. Primed here, before the log opens (R3), so a prompt is never garbled by tee.
plan_prime_sudo

plan_start_log auto

# The report lands in the per-run directory (R10): inside the repo so the agent reads it at
# the same path the operator sees, gitignored by the "*-runs/" rule so a dump of host state is
# never committed, and per-run so nothing overwrites earlier evidence.
REPORT="${PLAN_RUN_DIR}/plan-00110-triage-report.md"
readonly REPORT

{
    printf '# Plan 00110 — host triage report\n\n'
    printf 'Generated by CLAUDE/Plan/00110-vm-lifecycle-acceptance-testing/triage.bash on the HOST.\n\n'
    printf 'READ THIS FOR: the T0.2 decision gate — sections 1 (KVM), 2 (lab filesystem) and\n'
    printf '3 (headroom for three bases). Sections 4-11 answer U1, U2, U4, U5, U7 and U8; where\n'
    printf 'a question needs a running guest it says DEFERRED and names the phase that answers it.\n\n'
    printf -- '- repo root (resolved from the script, not the cwd): %s\n' "${PLAN_REPO_ROOT}"
    printf -- '- run directory: %s\n' "${PLAN_RUN_DIR}"
} >"${REPORT}"

plan_gather_leg "VM lab host prerequisites and the Phase-0 unknowns" \
    bash "${PLAN_SCRIPT_DIR}/probe-vm-lab-host.bash" "${REPORT}"

plan_finish
