#!/usr/bin/env bash
# Plan 00143 — triage.bash
#
# PURPOSE: gather grounded FACTS about the pointer path (touchpad, TrackPoint, kernel
# interrupts, libinput, GPU power state, compositor) so a lag episode can be pinned to a layer.
# Fact-finding only — it renders no verdict and changes nothing (PlanScriptStandards R9).
#
# RUN ON THE HOST, ideally WHILE THE POINTER IS LAGGING:
#   ./CLAUDE/Plan/00143-pointer-lag-and-trackpoint-speed/triage.bash               # instant snapshot
#   ./CLAUDE/Plan/00143-pointer-lag-and-trackpoint-speed/triage.bash --capture 20  # + 20s live capture
#
# With --capture, keep moving the touchpad and then the TrackPoint for the whole capture. It
# records libinput event timing for the POINTER devices only; the keyboard is never opened.
# Reading /dev/input needs root, so --capture primes sudo once, before the log opens.
#
# EFFECT ON THE HOST: READ-ONLY. Output goes to untracked/plan-runs/, which is never committed.
# --capture adds a private kernel tracing instance for its duration and removes it on exit,
# including on Ctrl-C, which stops every recorder.
#
# EXIT CODES:
#   0  every probe reached a definite answer
#   1  at least one probe could not be answered; the failing leg names itself
#  64  usage error
set -euo pipefail

# ── R1 bootstrap: script-relative, filesystem-only, bounded at the repo boundary ──────────
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage.bash [--capture <seconds>] [-h|--help]

Snapshot of the pointer path: load, compositor threads, displays, dGPU power
state, thermals, TrackPoint and GNOME pointer settings, libinput quirks for
this model, and the last 30 minutes of kernel and gnome-shell logs.

--capture <seconds>  additionally sample interrupt/ACPI/throttle/dGPU rates per
                     second and record libinput pointer-event timing. Run it
                     while the lag is happening and keep the pointer moving.

Host-only, read-only, safe to re-run."

plan_mode gather
plan_parse_common_flags "$@"

CAPTURE_SECS=""
set -- "${PLAN_REMAINING_ARGS[@]+"${PLAN_REMAINING_ARGS[@]}"}"
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        --capture)
            if [[ ! "${2:-}" =~ ^[1-9][0-9]*$ ]]; then
                printf '[FATAL] --capture needs a whole number of seconds\n%s\n' "${PLAN_USAGE}" >&2
                exit 64
            fi
            CAPTURE_SECS="$2"
            shift 2
            ;;
        *)
            printf '[FATAL] unknown argument: %s\n%s\n' "$1" "${PLAN_USAGE}" >&2
            exit 64
            ;;
    esac
done

plan_require_host "it reads the host's input devices, interrupts, GPU power state and journal"
if [[ -n "${CAPTURE_SECS}" ]]; then
    plan_prime_sudo
fi
plan_start_log auto

REPORT="${PLAN_RUN_DIR}/plan-00143-triage-report.md"
readonly REPORT
{
    printf '# Plan 00143 — pointer triage report\n\n'
    printf 'Generated by triage.bash on the HOST. Unscrubbed; never commit it.\n'
} >"${REPORT}"

# The capture leg runs as a waited-on background job so that its PID is known. A Ctrl-C, or
# a TERM sent to this script alone (the only way to stop a run an agent started in the
# background, where SIGINT is ignored from the start), then reaches it: the library's handler
# runs stop_capture before draining the log, and the leg stops its own recorders on TERM.
CAPTURE_PID=""
stop_capture() {
    local rc
    if [[ -z "${CAPTURE_PID}" ]]; then return 0; fi
    kill -TERM "${CAPTURE_PID}"
    if wait "${CAPTURE_PID}"; then rc=0; else rc=$?; fi
    printf '[teardown] capture leg stopped (rc=%s)\n' "${rc}" >&2
    CAPTURE_PID=""
}
plan_on_cleanup stop_capture

plan_gather_leg "pointer-path snapshot" \
    bash "${PLAN_SCRIPT_DIR}/probe-pointer.bash" snapshot "${REPORT}"
if [[ -n "${CAPTURE_SECS}" ]]; then
    bash "${PLAN_SCRIPT_DIR}/probe-pointer.bash" capture "${REPORT}" "${CAPTURE_SECS}" "${PLAN_RUN_DIR}" &
    CAPTURE_PID=$!
    plan_gather_leg "live capture (${CAPTURE_SECS}s)" wait "${CAPTURE_PID}"
    CAPTURE_PID=""
fi
stop_capture # a no-op once the leg has been reaped; the same call is what a signal runs

printf '==> READ FIRST: the "cursor on the panel", "libinput motion-event timing" and "per-second rates" sections\n'
plan_finish
