#!/usr/bin/env bash
# Plan 00144 — triage.bash
#
# PURPOSE: gather grounded FACTS about the before state of the two fedora-desktop panel
# extensions: which uuids are in `enabled-extensions`, which directories are deployed, whether
# the container-watch report exists, and the container-watch timer state. Fact-finding only —
# it renders no verdict and changes nothing (CLAUDE/PlanScriptStandards.md R9). The pass/fail
# gate is acceptance.bash.
#
# RUN ON THE HOST, from a graphical login session (it reads the session's dconf and runtime
# directory):
#   ./CLAUDE/Plan/00144-single-fedora-desktop-panel-icon/triage.bash
#
# EFFECT ON THE HOST: every leg is READ-ONLY. Re-runnable; each run has its own directory.
#
# EXIT CODES:
#   0  every probe reached a definite answer
#   1  at least one probe could not run (the fact-finding is incomplete, not the system broken)
#  64  usage error
set -euo pipefail

scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage.bash [-h|--help]

Gathers the before state of the container-watch and fedora-desktop panel extensions:
enabled-extensions membership, deployed directories, report.json presence, timer state.
Host-only, read-only, safe to re-run. The report is written to the per-run directory
under untracked/plan-runs/ and named on completion."

plan_mode gather
plan_parse_common_flags "$@"

if [[ "${#PLAN_REMAINING_ARGS[@]}" -gt 0 ]]; then
    printf '[FATAL] unknown argument(s): %s\n' "${PLAN_REMAINING_ARGS[*]}" >&2
    printf '%s\n' "${PLAN_USAGE}" >&2
    exit 64
fi

plan_require_host "it reads the host session's dconf, runtime directory and systemd --user manager"

plan_start_log auto

REPORT="${PLAN_RUN_DIR}/plan-00144-triage-report.md"
readonly REPORT
{
    printf '# Plan 00144 - triage report\n\n'
    printf 'Generated by triage.bash on the HOST. Facts only; no verdict.\n\n'
} >"${REPORT}"

# Legs are commands, not local functions (SC2317 cannot be suppressed here).
plan_gather_leg "enabled-extensions membership" \
    bash "${PLAN_SCRIPT_DIR}/probe-state.bash" "${REPORT}" enabled
plan_gather_leg "deployed extension directories" \
    bash "${PLAN_SCRIPT_DIR}/probe-state.bash" "${REPORT}" deployed
plan_gather_leg "container-watch report.json and backend CLI" \
    bash "${PLAN_SCRIPT_DIR}/probe-state.bash" "${REPORT}" report
plan_gather_leg "container-watch timer" \
    bash "${PLAN_SCRIPT_DIR}/probe-state.bash" "${REPORT}" timer

plan_finish
