#!/usr/bin/env bash
# Plan 00112 — triage.bash
#
# PURPOSE: record what the host's GNOME extension state IS, so Task 2.1's claim that the
# deploy removed nothing from the enabled list is a comparison of two recorded facts rather
# than an assertion. Run it BEFORE deploy.bash and again AFTER; the two reports are the
# evidence.
#
# Read-only. HOST ONLY (CLAUDE/PlanScriptStandards.md R2) — the questions are about a live
# GNOME session, which a container does not have.
#
# EXIT STATUS
#   0  every question answered
#   1  at least one leg could not answer; the failing leg names itself. The FACT-FINDING is
#      incomplete — it does not mean the host is misconfigured.
#  64  usage error
set -euo pipefail

# ── R1 bootstrap: script-relative, filesystem-only, bounded at the repo boundary ──────────
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage.bash [-h|--help]

Records the host's GNOME extension state: the deployed UUIDs, the current
org.gnome.shell enabled-extensions list, disable-user-extensions, each
extension's live State, and the system extensions under
/usr/share/gnome-shell/extensions.

Host-only and read-only. Safe to re-run. Run it before AND after deploy.bash so
'the deploy removed nothing' is a comparison, not a claim. Writes a report into
<this plan folder>/triage-runs/<timestamp>/ and names it on completion."

plan_mode gather
plan_parse_common_flags "$@"

if [[ "${#PLAN_REMAINING_ARGS[@]}" -gt 0 ]]; then
    printf '[FATAL] unknown argument(s): %s\n' "${PLAN_REMAINING_ARGS[*]}" >&2
    printf '%s\n' "${PLAN_USAGE}" >&2
    exit 64
fi

plan_require_host "the questions are about this machine's live GNOME session and dconf database"

plan_start_log auto

# The report lands in the per-run directory (R10): inside the repo so the agent reads it at
# the path the operator sees, gitignored by the "*-runs/" rule so host state is never
# committed, and per-run so a second run never overwrites the first — which is the whole
# point, since the before/after pair is the evidence.
REPORT="${PLAN_RUN_DIR}/plan-00112-extension-state-report.md"
readonly REPORT

{
    printf '# Plan 00112 — GNOME extension state report\n\n'
    printf 'Generated by CLAUDE/Plan/00112-gnome-extensions-enabled-state-declared/triage.bash on the HOST.\n\n'
    printf 'READ THIS FOR: Task 2.1. Section 2 is the enabled list the deploy must ADD to and\n'
    printf 'never subtract from — compare the before and after runs. Section 3 is what is\n'
    printf 'deployed and whether GNOME has it live. Section 4 is dash-to-dock evidence.\n\n'
    printf -- '- repo root (resolved from the script, not the cwd): %s\n' "${PLAN_REPO_ROOT}"
    printf -- '- run directory: %s\n' "${PLAN_RUN_DIR}"
} >"${REPORT}"

plan_gather_leg "GNOME extension state" \
    bash "${PLAN_SCRIPT_DIR}/probe-gnome-extensions.bash" "${REPORT}"

plan_finish
