#!/bin/bash

# Colors
end="\033[0m"
black="\033[0;30m"
blackBold="\033[1;30m"
white="\033[0;37m"
whiteBold="\033[1;37m"
red="\033[0;31m"
redBold="\033[1;31m"
green="\033[0;32m"
greenBold="\033[1;32m"
yellow="\033[0;33m"
yellowBold="\033[1;33m"
blue="\033[0;34m"
blueBold="\033[1;34m"
purple="\033[0;35m"
purpleBold="\033[1;35m"
lightblue="\033[0;36m"
lightblueBold="\033[1;36m"

function black {
  echo -e "${black}${1}${end}"
}

function blackBold {
  echo -e "${blackBold}${1}${end}"
}

function white {
  echo -e "${white}${1}${end}"
}

function whiteBold {
  echo -e "${whiteBold}${1}${end}"
}

function red {
  echo -e "${red}${1}${end}"
}

function redBold {
  echo -e "${redBold}${1}${end}"
}

function green {
  echo -e "${green}${1}${end}"
}

function greenBold {
  echo -e "${greenBold}${1}${end}"
}

function yellow {
  echo -e "${yellow}${1}${end}"
}

function yellowBold {
  echo -e "${yellowBold}${1}${end}"
}

function blue {
  echo -e "${blue}${1}${end}"
}

function blueBold {
  echo -e "${blueBold}${1}${end}"
}

function purple {
  echo -e "${purple}${1}${end}"
}

function purpleBold {
  echo -e "${purpleBold}${1}${end}"
}

function lightblue {
  echo -e "${lightblue}${1}${end}"
}

function lightblueBold {
  echo -e "${lightblueBold}${1}${end}"
}


