#!/usr/bin/env bash
# Plan 00138 — triage.bash
#
# PURPOSE: gather grounded FACTS about how bash history is configured and behaving on
# this host — which init files set what, what a fresh terminal really ends up with, the
# shape of ~/.bash_history, and which Ctrl+R tools are present. Fact-finding only — it
# renders no verdict and changes nothing (CLAUDE/PlanScriptStandards.md R9).
#
# RUN ON THE HOST, as the desktop user:
#   ./CLAUDE/Plan/00138-bash-history-and-ctrl-r/triage.bash
#
# EFFECT ON THE HOST: every leg is READ-ONLY. It never prints a history line — only
# counts, sizes and timestamps — because history holds typed secrets.
#
# Usage: ./triage.bash [-h|--help]
#
# EXIT CODES:
#   0  every probe reached a definite answer
#   1  at least one probe could not be answered; the failing leg names itself. This means
#      the FACT-FINDING is incomplete, not that history is broken.
#  64  usage error
set -euo pipefail

# ── R1 bootstrap: script-relative, filesystem-only, bounded at the repo boundary ──────────
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repoRoot="${scriptDir}"
while [[ "${repoRoot}" != "/" ]] && [[ ! -e "${repoRoot}/ansible.cfg" ]]; do
    if [[ -e "${repoRoot}/.git" ]]; then
        printf '[FATAL] no ansible.cfg between %s and the repo root %s\n' "${scriptDir}" "${repoRoot}" >&2
        exit 1
    fi
    repoRoot="$(dirname "${repoRoot}")"
done
[[ -e "${repoRoot}/ansible.cfg" ]] || {
    printf '[FATAL] no ansible.cfg above %s\n' "${scriptDir}" >&2
    exit 1
}
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../_planlib.inc.bash
source "${repoRoot}/CLAUDE/Plan/_planlib.inc.bash"
plan_init "${BASH_SOURCE[0]}"

PLAN_USAGE="usage: triage.bash [-h|--help]

Gathers facts about bash history: the init files that configure it, the
effective settings in a fresh interactive shell, the shape (never the
contents) of ~/.bash_history, and the Ctrl+R tools installed.

Host-only, read-only, safe to re-run. Writes a report under
untracked/plan-runs/ and names it on completion."

plan_mode gather
plan_parse_common_flags "$@"

if [[ "${#PLAN_REMAINING_ARGS[@]}" -gt 0 ]]; then
    printf '[FATAL] unknown argument(s): %s\n' "${PLAN_REMAINING_ARGS[*]}" >&2
    printf '%s\n' "${PLAN_USAGE}" >&2
    exit 64
fi

plan_require_host "it reads the host user's shell init files and history file"

plan_start_log auto

REPORT="${PLAN_RUN_DIR}/plan-00138-triage-report.md"
readonly REPORT

{
    printf '# Plan 00138 — triage report\n\n'
    printf 'Generated by CLAUDE/Plan/00138-bash-history-and-ctrl-r/triage.bash on the HOST.\n\n'
    printf -- '- repo root (resolved from the script, not the cwd): %s\n' "${PLAN_REPO_ROOT}"
    printf -- '- run directory: %s\n' "${PLAN_RUN_DIR}"
} >"${REPORT}"

plan_gather_leg "history settings, init files, history file shape, Ctrl+R tools" \
    bash "${PLAN_SCRIPT_DIR}/probe-history.bash" "${REPORT}"

plan_finish
