#!/usr/bin/env ansible-playbook
---
- hosts: desktop
  name: Gnome Shell Extensions
  become: true
  vars:
    root_dir: "{{ lookup('ansible.builtin.config', 'CONFIG_FILE') | dirname }}"
  tasks:
    - name: Install Packages
      ansible.builtin.dnf:
        name:
          - gnome-tweaks.noarch
