#!/usr/bin/env ansible-playbook
---
- hosts: desktop
  name: Preflight Sanity
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  vars_files:
    - "{{ root_dir }}/vars/fedora-version.yml"
  tasks:
    - name: Check Ansible
      ansible.builtin.assert:
        that:
          - ansible_version.full is version('2.20', '>=')
        fail_msg: |
          This project requires Ansible 2.20 or greater

    - name: Check Fedora
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] == 'RedHat'
          - ansible_facts['distribution'] == 'Fedora'
          - ansible_facts['distribution_major_version'] | int == fedora_version | int
        fail_msg: "This project expects Fedora {{ fedora_version }}"
