#!/usr/bin/env ansible-playbook
---
# This play installs things you need for Golang development
- hosts: desktop
  vars:
    root_dir: "{{ lookup('ansible.builtin.config', 'CONFIG_FILE') | dirname }}"
  tasks:
    - name: Install Golang
      become: true
      ansible.builtin.dnf:
        name: golang
