- hosts: desktop
  name: Last Pass
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  vars_prompt:
    - name: "lastpass_username"
      prompt: "Enter your lastpass username"
      private: no
  tasks:
    - name: Install Lastpass
      become: true
      dnf:
        name: lastpass-cli
        state: present

    - name: Login to Lastpass
      shell: |
        set -ex
        lpass login "{{ lastpass_username }}"
        lpass sync
