#!/usr/bin/env ansible-playbook
- hosts: desktop
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Set Controller Mode to bredr to Fix Bluetooth Headphones
      become: true
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED: Set Controller Mode to bredr to Fix Bluetooth Headphones"
        block: |
          ControllerMode = bredr
        path: /etc/bluetooth/main.conf
        insertafter: \[General\]
      notify: restart-bt

    - name: Create WirePlumber configuration directory
      become: true
      file:
        path: /etc/wireplumber/wireplumber.conf.d
        state: directory
        mode: '0755'

    - name: Configure Bluetooth settings for WirePlumber 0.5+
      become: true
      blockinfile:
        path: /etc/wireplumber/wireplumber.conf.d/50-bluetooth.conf
        marker: "# {mark} ANSIBLE MANAGED: Bluetooth Headphones Quality Settings"
        create: true
        mode: '0644'
        block: |
          monitor.bluez.properties = {
            bluez5.enable-sbc-xq = true
            bluez5.enable-msbc = true
            bluez5.enable-hw-volume = true
            bluez5.headset-roles = [ hsp_hs hsp_ag hfp_hf hfp_ag ]
            bluez5.codecs = [ sbc sbc_xq aac ldac aptx aptx_hd aptx_ll aptx_ll_duplex ]
            bluez5.default.rate = 48000
            bluez5.a2dp.ldac.quality = hq
          }
      notify: restart-pw

  handlers:
    - name: restart-pw
      systemd:
        scope: user
        name: pipewire
        state: restarted

    - name: restart-bt
      become: true
      systemd:
        name: bluetooth
        state: restarted
